CREATE TABLE DUMMY_USER.EXAMPLE_COMPRESSED_TABLE
(
  COLUMN1    VARCHAR2(1 BYTE),
  COLUMN2   VARCHAR2(30 BYTE),
  COLUMN3      CLOB,
  COLUMN4    NUMBER(6),
  COLUMN5        DATE,
  COLUMN6       NUMBER(4),
  COLUMN7       VARCHAR2(1000 BYTE),
  COLUMN8       VARCHAR2(15 BYTE),
  COLUMN9   VARCHAR2(128 BYTE),
  COLUMN10  VARCHAR2(20 BYTE)
)
LOB (COLUMN3) STORE AS SECUREFILE (
  TABLESPACE  DUMMY_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  DEDUPLICATE
  COMPRESS    MEDIUM
  PCTVERSION  10
  NOCACHE
  NOLOGGING)
ROW STORE COMPRESS ADVANCED 
TABLESPACE DUMMY_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (COLUMN5)
INTERVAL( NUMTODSINTERVAL(1,'COLUMN5'))
(  
  PARTITION VALUES LESS THAN (TO_DATE(' 2015-01-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    ROW STORE COMPRESS ADVANCED
    TABLESPACE DUMMY_TS
    LOB (COLUMN3) STORE AS SECUREFILE (
      TABLESPACE  DUMMY_TS
      ENABLE      STORAGE IN ROW
      CHUNK       8192
	  DEDUPLICATE
	  COMPRESS	  MEDIUM
      RETENTION
      NOCACHE
      NOLOGGING)
    PCTFREE    0
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                MAXSIZE          UNLIMITED
                BUFFER_POOL      DEFAULT
               )
);
